Deploy properties along with artifacts
anancarv/python-artifactory pull request #190
Opened 2024-09-18 16:33 UTC by aslheyrr

## Description

Artifactory REST API supports deploying artifacts and properties in a single operation. This is particularly useful so that you don't have to make any additional API calls to set properties.

This PR enables the deployment of artifacts and properties (optional parameter) in the same request.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How has it been tested ?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] My PR is ready for prime time! Otherwise use the ["Draft PR" feature](https://help.github.com/en/articles/about-pull-requests#draft-pull-requests)
- [x] All commits have a correct title
- [x] Readme has been updated
- [x] Quality tests are green (see Codacy)
- [x] Automated tests are green (see pipeline)

2024-09-18 21:34 UTC, anancarv commented
Hey @aslheyrr,
I do not see that feature on the [Artifactory API](https://jfrog.com/help/r/jfrog-rest-apis/deploy-artifact-apis). Can you please point me to the corresponding documentation?

2024-09-19 13:44 UTC, aslheyrr commented
Hi @anancarv 
This is where I found it https://jfrog.com/help/r/jfrog-artifactory-documentation/using-properties-in-deployment-and-resolution

2024-09-19 16:08 UTC, anancarv requested changes
There are just some minor changes required. But the MR looks good

2024-09-19 20:35 UTC, aslheyrr commented on pyartifactory/objects/artifact.py
> +        return properties_param_str
Done

2024-09-19 20:35 UTC, aslheyrr commented on README.md
> +# artifact = art.artifacts.deploy("Desktop/myNewFile.txt", "my-repository/my/new/artifact/directory/file.txt", {"retention": "30"})
Fixed!

2024-09-20 07:50 UTC, anancarv approved these changes
lgtm!

2024-09-20 08:17 UTC, merged