Removing SecretStr from RemoteRepository model
anancarv/python-artifactory pull request #75
Opened 2020-12-02 23:58 UTC by ajrpeggio

SecretStr is not JSON serializable and is throwing exceptions for RemoteRepositories that require a password.

## Description
I've been using this library to create repositories for my Artifactory Instance. I started adding a RemoteRepository for docker and came upon this error that states: "Object of type SecretStr is not JSON serializable"

## To Reproduce
Steps to reproduce the behavior:

```python
from pyartifactory import Artifactory
from pyartifactory.models import RemoteRepository

url = <url to artifactory instance>
auth = (<username>, <password>)
remote_docker_repo_cfg = {
    "key": "docker-remote",
    "url": "https://registry-1.docker.io/",
    "packageType": "docker",
    "username": <dockerhub username>,
    "password": <dockerhub_password>,
}
rt = Artifactory(url=url, auth=auth)
remote_repo = RemoteRepository(**remote_docker_repo_cfg)
rt.repositories.create_repo(remote_repo)
```

Fixes # https://github.com/anancarv/python-artifactory/issues/74

2020-12-03 09:03 UTC, anancarv commented
Hi @ajrpeggio ,
After running some tests. It appears that you can keep the `SecretStr` from the `RemoteRepository` model. Also, changing it to str would decrease the level of security and our password will be able to be read.
Instead, in the `objects.py` file, you can change the following line:
`self._put(f"api/{self._uri}/{repo_name}", json=repo.dict())` to `self._put(f"api/{self._uri}/{repo_name}", json=repo.json())`

Indead, .json() will be able to serialize the SecretStr param

2020-12-03 13:26 UTC, anancarv commented
Hi @ajrpeggio,
After running some tests. It appears that it's better to keep the `SecretStr` type in the RemoteRepository model. Indeed, changing it to `str` will decrease the level of security and your password will be able to be printed.

A better solution is t create a custom encoder in a `utils.py` file for example with the following content:
```
import json
from pydantic import SecretStr
from pydantic.json import pydantic_encoder

def custom_encoder(obj):
      if isinstance(obj, SecretStr):
          return obj.get_secret_value()
      else:
          return pydantic_encoder(obj)
```

Then in the `objects.py` file, in the file 466 you can replace:
```
self._put(f"api/{self._uri}/{repo_name}", json=repo.dict())
```
with
```
data= json.dumps(repo, default=custom_encoder)
self._put(f"api/{self._uri}/{repo_name}", headers={"Content-Type": "application/json"}, data=data)
```

2020-12-04 09:03 UTC, anancarv requested changes

2020-12-04 09:03 UTC, anancarv commented on pyartifactory/utils.py
> +        return pydantic_encoder(obj)
It seems that you haven't run the `pre-commits`. If you had, you could have seen the following errors:
```
pyartifactory/utils.py:1:0: C0114: Missing module docstring (missing-module-docstring)
pyartifactory/utils.py:5:0: C0116: Missing function or method docstring (missing-function-docstring)
pyartifactory/utils.py:6:4: R1705: Unnecessary "else" after "return" (no-else-return)
```

Can be fixed with:
```
"""
Definition of all utils.
"""

from typing import Any

from pydantic import SecretStr
from pydantic.json import pydantic_encoder


def custom_encoder(obj: Any) -> Any:
    """
    Custom encoder function to be passed to the default argument of json.dumps()
    :param obj: A pydantic object
    :return: An encoded pydantic object
    """
    if isinstance(obj, SecretStr):
        return obj.get_secret_value()
    return pydantic_encoder(obj)
```

2020-12-04 09:03 UTC, anancarv commented on pyartifactory/objects.py
> +            data= json.dumps(repo, default=custom_encoder)
The pre-commits also highlight formatting issue in this line. Indeed `data=` should be `data =`

2020-12-04 09:06 UTC, anancarv commented
Also, there are conflicts with the master branch. Indeed, a new release has been merged a few days ago. You will also need to fix the conflicts before merging

2020-12-10 13:47 UTC, anancarv commented
Hi @ajrpeggio ,
Are you facing troubles with the changes requested ? Would you prefer me to it ?

2020-12-14 12:55 UTC, anancarv approved these changes

2020-12-15 09:58 UTC, nymous approved these changes
Let's go!

2020-12-15 10:49 UTC, merged

2020-12-15 15:56 UTC, ajrpeggio commented
Apologies for getting back to this so late. Thank you for fixing these!

2020-12-15 16:07 UTC, anancarv commented
No worries. You're welcome !